name: CI

on: [push, pull_request]

jobs:
  Python Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: |
        python -m unittest discover -s src/python -p "*_test.py"
 
  build:
    name: c build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          mkdir cmake-build
          cd cmake-build
          cmake ../src/c
          make 
