name: CI
# ToDo: This should be shifted to a docker container, so there is SWIG available
on: [push, pull_request]

jobs:
  python_unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      # Use Cache, see: https://github.com/actions/cache
      if: startsWith(runner.os, 'Linux')
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
      
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        SRC_DIR=$(pwd)
        python -m pip install --upgrade pip
        cd python
        pip install -r requirements.txt

    - name: Install SWIG
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        wget http://prdownloads.sourceforge.net/swig/swig-4.0.1.tar.gz
        tar -xf swig-4.0.1.tar.gz
        cd swig-4.0.1
        ./configure
        make
        # Append to path
        PATH=$PATH:$(pwd)
        cd $(SRC_DIR)

    - name: Try Build
      run: python setup.py sdist bdist_wheel

    - name: Test
      run: python setup.py test