name: CI
# ToDo: This should be shifted to a docker container, so there is SWIG available
on: [push, pull_request]

jobs:
  python_unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - uses: actions/cache@v1
      # Use Cache, see: https://github.com/actions/cache
      if: startsWith(runner.os, 'Linux')
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements.txt
        pip install pytest tox

    - name: Install SWIG (Linux)
      if: runner.os == 'Linux'
      run: |
        # sudo apt-get install swig
        mkdir swig
        cd swig
        wget http://prdownloads.sourceforge.net/swig/swig-4.0.1.tar.gz
        tar -xf swig-4.0.1.tar.gz
        cd swig-4.0.1
        ./configure
        make
        sudo make install
        
    - name: Try Build
      run: |
        cd python
        python setup.py build
        python setup.py build_ext --build-lib .
        python setup.py sdist bdist_wheel

    - name: Test
      run: |
        cd python
        # tox
        pytest
        
