name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
  
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        SRC_DIR=$(pwd)
        cd python
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install SWIG
      run: |
        wget http://prdownloads.sourceforge.net/swig/swig-4.0.1.tar.gz
        tar -xf swig-4.0.1.tar.gz
        cd swig-4.0.1
        ./configure
        make
        # Append to path
        PATH=$PATH:$(pwd)
        cd $(SRC_DIR)

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
        python setup.py test

    - name: Test Install
      run: |
        python setup.py sdist bdist_wheel
        pip install .