name: VHDL Testbenches

on: [push, pull_request]

jobs:
  vhdl_testbenches:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - uses: actions/cache@v1
      # Use Cache, see: https://github.com/actions/cache
      if: startsWith(runner.os, 'Linux')
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install GHDL
      run: |
        sudo apt-get update
        sudo apt-get install llvm libgnat-6 libc6 # Used by 
        
        # Install GHDL
        mkdir ghdl
        cd ghdl
        wget https://github.com/ghdl/ghdl/releases/download/v0.36/ghdl-0.36-ubuntu14-llvm-3.8.tgz
        tar -xf ghdl-0.36-ubuntu14-llvm-3.8.tgz
        # Find better way to install
        chmod +x bin/*
        sudo mv bin/* /usr/local/bin
        sudo mv lib/* /usr/local/lib
        sudo mv include/* /usr/local/include

        # Check if ghdl is in path
        ghdl --version

        # sudo dpkg --install ghdl_0.33-1ubuntu1_amd64.deb
        # sudo apt-get install ghdl
  
    - name: Install Python Dependencies
      run: |
        pwd        
        python -m pip install --upgrade pip
        pip install -r vivado/requirements.txt

    - name: Test
      run: |
        pwd
        cd vivado/NN_IP/EggNet_1.0/sim/MemCtrl/
        python tb_MemCtrl_run_sim.py
